[package]
name = "arc"
authors = ["Nathan Aronson"]
description = "A bytecode-compiled programming language with a virtual machine written in Rust."
version = "0.1.0"
edition = "2024"

[dependencies]
